// File generated by FlutterFire CLI; iOS uses Firebase app `NexRide Merchant iOS`
// (bundle ID `com.nexride.merchant`). Android uses the merchant Android client in
// `android/app/google-services.json` — keep both in sync with project `nexride-8d5bc`.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Configure web via FlutterFire CLI for nexride_merchant.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const String defaultRealtimeDatabaseUrl =
      'https://nexride-8d5bc-default-rtdb.firebaseio.com';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKbsKmUCfq0ylIAuekiVko_Gu6wWQse4',
    appId: '1:684231437366:android:6eea081d5d004ff4ec3c97',
    messagingSenderId: '684231437366',
    projectId: 'nexride-8d5bc',
    storageBucket: 'nexride-8d5bc.firebasestorage.app',
    databaseURL: defaultRealtimeDatabaseUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYXBPJpPZ819PKkx3QiKAg9wPpeXMeUs',
    appId: '1:684231437366:ios:118d3396963f7a80ec3c97',
    messagingSenderId: '684231437366',
    projectId: 'nexride-8d5bc',
    storageBucket: 'nexride-8d5bc.firebasestorage.app',
    iosBundleId: 'com.nexride.merchant',
    databaseURL: defaultRealtimeDatabaseUrl,
  );
}
