// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Same default Realtime Database as driver app / FlutterFire web — keep in sync.
  static const String defaultRealtimeDatabaseUrl =
      'https://nexride-8d5bc-default-rtdb.firebaseio.com';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPKbsKmUCfq0ylIAuekiVko_Gu6wWQse4',
    appId: '1:684231437366:android:b0729b7486025abcec3c97',
    messagingSenderId: '684231437366',
    projectId: 'nexride-8d5bc',
    storageBucket: 'nexride-8d5bc.firebasestorage.app',
    databaseURL: defaultRealtimeDatabaseUrl,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYXBPJpPZ819PKkx3QiKAg9wPpeXMeUs',
    appId: '1:684231437366:ios:90c8c38db39a5e91ec3c97',
    messagingSenderId: '684231437366',
    projectId: 'nexride-8d5bc',
    storageBucket: 'nexride-8d5bc.firebasestorage.app',
    iosBundleId: 'com.nexride.rider',
    databaseURL: defaultRealtimeDatabaseUrl,
  );
}
