#!/usr/bin/env node
/**
 * scripts/reset_admin_password.js
 *
 * Reset a Firebase Auth user's password using the Admin SDK.
 *
 * Why this exists:
 *   The public sign-in API (`signInWithEmailAndPassword`) is rate-limited per
 *   client IP after a small number of failed attempts. Once that throttle
 *   trips, the user-facing "Forgot password" flow can also stall. The Admin
 *   SDK runs server-side with a service-account credential and is NOT subject
 *   to the same throttle, so this script is the safe escape hatch when an
 *   operator is locked out of /admin or /support.
 *
 * What this script does:
 *   1. Loads a service-account credential (env > scripts/serviceAccountKey.json > ADC).
 *   2. Looks up the Firebase Auth user by email.
 *   3. Sets a new password (provided via flag, env, or generated in-memory).
 *   4. Revokes all existing refresh tokens so every existing session must
 *      re-authenticate (defends against a session having been stolen).
 *   5. Prints a clean success block. The password is only printed if it was
 *      generated by this script.
 *
 * Password sources (first match wins):
 *   1. CLI:  --password "..."  (or --password=... )
 *   2. Env:  NEW_PASSWORD='...'
 *   3. Generated 24-char random (~144 bits entropy), printed once.
 *
 * Credential sources (first match wins):
 *   1. GOOGLE_APPLICATION_CREDENTIALS=/abs/path/serviceAccountKey.json
 *   2. scripts/serviceAccountKey.json   (added to .gitignore)
 *   3. Application Default Credentials  (`gcloud auth application-default login`)
 *
 * Examples:
 *   # Reset the locked-out owner account using a password from env (preferred):
 *   NEW_PASSWORD='NexRideAdmin#2026!' node scripts/reset_admin_password.js \
 *       nexrideinfo@gmail.com
 *
 *   # Reset any user, let the script generate a strong random password:
 *   node scripts/reset_admin_password.js admin@nexride.africa
 *
 *   # Use an explicit service-account file:
 *   GOOGLE_APPLICATION_CREDENTIALS=/Users/me/secrets/nexride-sa.json \
 *       node scripts/reset_admin_password.js nexrideinfo@gmail.com
 *
 * Security notes:
 *   - DO NOT pass the password directly on the command line if you can avoid
 *     it; many shells log it to ~/.zsh_history. Use the env-var form above.
 *   - DO NOT commit serviceAccountKey.json — it's already gitignored.
 *   - This script does NOT modify roles, claims, or RTDB. It only resets the
 *     login password for a user that already exists. To create new admins,
 *     use scripts/create_admin_user.js.
 */

"use strict";

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const admin = require("firebase-admin");

const PROJECT_ID = "nexride-8d5bc";
const DATABASE_URL = "https://nexride-8d5bc-default-rtdb.firebaseio.com";
const DEFAULT_EMAIL = "nexrideinfo@gmail.com";
const MIN_PASSWORD_LENGTH = 12;

function parseCli(argv) {
  const args = argv.slice(2);
  let email = null;
  let password = null;
  for (let i = 0; i < args.length; i += 1) {
    const v = args[i];
    if (v === "--password" || v === "-p") {
      password = args[i + 1];
      i += 1;
    } else if (v.startsWith("--password=")) {
      password = v.slice("--password=".length);
    } else if (v === "--help" || v === "-h") {
      printHelp();
      process.exit(0);
    } else if (!v.startsWith("-") && !email) {
      email = v;
    }
  }
  return { email: email || DEFAULT_EMAIL, password };
}

function printHelp() {
  console.log(
    "Usage: node scripts/reset_admin_password.js [email] [--password <pw>]\n" +
      "\n" +
      "  email           Email of the Firebase Auth user (default: " +
      DEFAULT_EMAIL +
      ").\n" +
      "  --password, -p  New password. Prefer NEW_PASSWORD env var to keep it\n" +
      "                  out of shell history. If neither is provided, a strong\n" +
      "                  random password is generated and printed once.\n",
  );
}

function generatePassword(length = 24) {
  return crypto
    .randomBytes(length * 2)
    .toString("base64")
    .replace(/[+/=]/g, "")
    .slice(0, length);
}

function configureCredentials() {
  if (process.env.GOOGLE_APPLICATION_CREDENTIALS) {
    return `env:GOOGLE_APPLICATION_CREDENTIALS=${process.env.GOOGLE_APPLICATION_CREDENTIALS}`;
  }
  const local = path.resolve(__dirname, "serviceAccountKey.json");
  if (fs.existsSync(local)) {
    process.env.GOOGLE_APPLICATION_CREDENTIALS = local;
    return `file:${local}`;
  }
  const adc = path.join(
    process.env.HOME || "",
    ".config/gcloud/application_default_credentials.json",
  );
  if (fs.existsSync(adc)) {
    process.env.GOOGLE_APPLICATION_CREDENTIALS = adc;
    return `file:${adc} (Application Default Credentials)`;
  }
  return null;
}

async function main() {
  const { email, password: providedPassword } = parseCli(process.argv);

  const credSource = configureCredentials();
  if (!credSource) {
    console.error(
      "[reset_admin_password] No service-account credentials found.\n" +
        "Provide one of:\n" +
        "  - GOOGLE_APPLICATION_CREDENTIALS=/abs/path/serviceAccountKey.json\n" +
        "  - scripts/serviceAccountKey.json   (gitignored)\n" +
        "  - gcloud auth application-default login\n" +
        "\n" +
        "See docs/admin_access.md for how to download a service-account key.",
    );
    process.exit(2);
  }

  admin.initializeApp({ projectId: PROJECT_ID, databaseURL: DATABASE_URL });

  const envPassword = String(process.env.NEW_PASSWORD || "").trim();
  let password = (providedPassword || envPassword || "").trim();
  let generated = false;
  if (!password) {
    password = generatePassword(24);
    generated = true;
  }

  if (password.length < MIN_PASSWORD_LENGTH) {
    console.error(
      `[reset_admin_password] Password must be at least ${MIN_PASSWORD_LENGTH} characters.`,
    );
    process.exit(2);
  }

  let user;
  try {
    user = await admin.auth().getUserByEmail(email);
  } catch (error) {
    console.error(
      `[reset_admin_password] No Firebase Auth user found for "${email}": ${
        error?.message || error
      }`,
    );
    process.exit(1);
  }

  await admin.auth().updateUser(user.uid, { password });
  await admin.auth().revokeRefreshTokens(user.uid);

  const banner = "=".repeat(64);
  console.log(banner);
  console.log("PASSWORD RESET SUCCEEDED");
  console.log(banner);
  console.log(`  email          : ${email}`);
  console.log(`  uid            : ${user.uid}`);
  console.log(`  refresh tokens : revoked (every existing session must sign in again)`);
  console.log(`  credentials    : ${credSource}`);
  console.log(`  project        : ${PROJECT_ID}`);
  if (generated) {
    console.log("");
    console.log("  Generated temporary password (printed ONLY here, never written to disk):");
    console.log(`  >>> ${password}`);
    console.log("");
    console.log("  Store it in 1Password / Bitwarden NOW, then change it on first login.");
  } else {
    console.log("  password       : (provided via --password or NEW_PASSWORD; not echoed)");
  }
  console.log(banner);
}

main().catch((error) => {
  console.error("[reset_admin_password] failed:", error?.message || error);
  process.exit(1);
});
